services:
  nexus:
    image: kkda82/nexus-prebuilt:latest
    container_name: nexus-node
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/ubuntu/.nexus:/root/.nexus
    network_mode: none
    tty: true
    stdin_open: true
