services:
  nexus:
    image: kkda82/nexus-prebuilt:latest
    container_name: nexus-node
    network_mode: "none"
    volumes:
      - /home/ubuntu/.nexus:/root/.nexus
    environment:
      - TZ=Asia/Seoul
    tty: true
    stdin_open: true
